# Generated by Django 4.2.3 on 2024-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_description_project_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="abstract",
            field=models.TextField(default="Abstract"),
        ),
    ]
